version: "3"

services:

  storage:
    image: "redis:5"
    ports:
      - "6379:6379"
    volumes:
      - "redis-data:/data"

  app:
    image: "instantor/fullstacktest"
    ports:
      - "8080:8080"
    environment:
      - "SPRING_REDIS_HOST=storage"
    depends_on:
      - storage

volumes:
  redis-data:
